export const displayNavigationItems = [
  { label: 'Home', href: '/display/home' },
  { label: 'Session', href: '/display/session/plan' },
  { label: 'Results', href: '/display/results/summary' },
  { label: 'Exercises', href: '/display/exercises/plan' },
  { label: 'Progress', href: '/display/progress' },
  { label: 'Reports', href: '/display/reports' },
  { label: 'Settings', href: '/display/settings' },
];

const displayRoutes = [
  {
    id: 'display_connect',
    namespace: 'display',
    path: '/display/connect',
    title: 'Connect Your Phone',
    eyebrow: 'Phone connection',
    instruction: 'Scan the QR code or enter the connection code.',
    description: 'Your phone will record your movement while this screen gives you clear instructions.',
    primaryAction: 'Refresh Code',
    secondaryAction: 'Connection Help',
    icon: 'i',
    status: 'Waiting for phone camera',
    cards: ['Secure one-time link', 'Profile stays on the phone', 'Camera stream starts after permission'],
  },
  {
    id: 'display_profile',
    namespace: 'display',
    path: '/display/profile',
    title: 'Who is using Steply today?',
    eyebrow: 'Profile',
    instruction: "Choose the profile for today's session.",
    description: 'Steply uses the profile only to show the right assessment guidance.',
    primaryAction: 'Continue',
    secondaryAction: 'Reconnect phone',
    icon: 'OK',
    status: 'Profile ready',
    cards: ['Name and age range', 'Usual walking support', 'Recent fall history'],
  },
  {
    id: 'display_onboarding',
    namespace: 'display',
    path: '/display/onboarding',
    title: 'Set Up Steply',
    eyebrow: 'First-time setup',
    instruction: 'Add basic information and safety preferences.',
    description: "Steply uses a few details to make today's session easier to follow.",
    primaryAction: 'Continue',
    secondaryAction: 'Back',
    icon: 'i',
    status: 'Ready to begin',
    cards: ['Clear instructions', 'Large buttons', 'Gentle pace'],
  },
  {
    id: 'display_home',
    namespace: 'display',
    path: '/display/home',
    title: 'Good morning',
    eyebrow: 'Home',
    instruction: 'Today includes a balance reassessment and your recommended exercises.',
    description: "Review today's plan, recent progress, and next reassessment.",
    primaryAction: "Start Today's Session",
    secondaryAction: 'View progress',
    icon: 'i',
    status: 'Session not started',
    cards: ['CDC STEADI screening', '4-Stage Balance Test', '30-Second Chair Stand Test'],
  },
  {
    id: 'display_session_plan',
    namespace: 'display',
    path: '/display/session/plan',
    title: "Today's Session",
    eyebrow: 'Session plan',
    instruction: 'Review the plan before starting setup.',
    description: 'This session includes a quick health check, safety setup, assessments, and recommended exercises.',
    primaryAction: 'Start Setup',
    secondaryAction: 'Return Home',
    icon: 'i',
    status: 'Planning',
    session: true,
    progress: { current: 1, total: 9 },
    cards: ['Screening questions', 'Safety check', 'Camera setup', 'Assessment', 'Results'],
  },
  {
    id: 'display_session_screening',
    namespace: 'display',
    path: '/display/session/screening',
    title: 'Health Check',
    eyebrow: 'CDC STEADI',
    instruction: 'Answer one question at a time.',
    description: "Your answers help prepare today's session.",
    primaryAction: 'Continue',
    secondaryAction: 'Previous Question',
    icon: 'i',
    status: 'Screening',
    session: true,
    progress: { current: 2, total: 9 },
    cards: ['Fallen in the past year', 'Feels unsteady', 'Worried about falling'],
  },
  {
    id: 'display_session_safety',
    namespace: 'display',
    path: '/display/session/safety',
    title: 'Safety Setup',
    eyebrow: 'Safety setup',
    instruction: 'Prepare the room before the camera assessment starts.',
    description: 'Confirm the support surface, chair, floor, clothing, and how you feel today.',
    primaryAction: "I'm Ready",
    secondaryAction: 'Show Setup Guide',
    icon: '!',
    status: 'Check safety first',
    session: true,
    progress: { current: 3, total: 9 },
    cards: ['Clear floor', 'Stable chair', 'Support nearby', 'Comfortable shoes'],
  },
  {
    id: 'display_session_camera_setup',
    namespace: 'display',
    path: '/display/session/camera-setup',
    title: 'Camera Setup',
    eyebrow: 'Camera setup',
    instruction: 'Use the live view to adjust the phone before calibration.',
    description: 'Continue only when the camera checks are ready.',
    primaryAction: 'Continue',
    secondaryAction: 'Check Camera',
    icon: 'i',
    status: 'Camera setup',
    session: true,
    progress: { current: 4, total: 9 },
    camera: true,
    cards: ['Full body visible', 'One person in view', 'Good lighting'],
  },
  {
    id: 'display_session_calibration',
    namespace: 'display',
    path: '/display/session/calibration',
    title: 'Stand Still for a Moment',
    eyebrow: 'Calibration',
    instruction: 'Stand upright, face the camera, and keep both feet still.',
    description: 'Calibration checks the camera position before assessment entry.',
    primaryAction: 'Continue',
    secondaryAction: 'Pause',
    icon: 'OK',
    status: 'Checking camera view',
    session: true,
    progress: { current: 5, total: 9 },
    camera: true,
    cards: ['Full body', 'Feet visible', 'Camera steady'],
  },
  {
    id: 'display_balance_instruction',
    namespace: 'display',
    path: '/display/assessment/balance/instruction',
    title: '4-Stage Balance Test',
    eyebrow: 'CDC STEADI',
    instruction: 'You will try four standing positions. Hold each position for up to 10 seconds.',
    description: 'Keep a stable table or countertop within reach.',
    primaryAction: 'Start Balance Test',
    secondaryAction: 'Watch Again',
    icon: 'i',
    status: 'Instruction',
    session: true,
    progress: { current: 6, total: 9 },
    cards: ['Feet Side by Side', 'Semi-Tandem Stand', 'Tandem Stand', 'One-Leg Stand'],
  },
  {
    id: 'display_balance_live',
    namespace: 'display',
    path: '/display/assessment/balance/live',
    title: '4-Stage Balance Test',
    eyebrow: '4-Stage Balance Test',
    instruction: 'Hold the detected position for up to 10 seconds.',
    description: 'The timer begins only when the correct position is detected.',
    primaryAction: 'Pause',
    secondaryAction: 'Hear Again',
    icon: '!',
    status: 'Timed assessment in progress',
    session: true,
    timed: true,
    active: true,
    progress: { current: 7, total: 9 },
    camera: true,
    cards: ['Timer running', 'Camera connected', 'Stop Session is always available'],
  },
  {
    id: 'display_balance_stage_result',
    namespace: 'display',
    path: '/display/assessment/balance/stage-result',
    title: 'Balance Stage Result',
    eyebrow: 'Stage result',
    instruction: 'Review this stage before moving to the next step.',
    description: 'The result shown here comes from the existing assessment pipeline.',
    primaryAction: 'Continue to Next Position',
    secondaryAction: 'Hear Again',
    icon: 'OK',
    status: 'Stage complete',
    session: true,
    progress: { current: 8, total: 9 },
    cards: ['Stage time', 'Camera quality', 'Next step'],
  },
  {
    id: 'display_chair_instruction',
    namespace: 'display',
    path: '/display/assessment/chair/instruction',
    title: '30-Second Chair Stand Test',
    eyebrow: 'CDC STEADI',
    instruction: 'Review the movement before checking your starting position.',
    description: 'Sit centered, keep both feet flat, and cross your arms over your chest.',
    primaryAction: 'Check Starting Position',
    secondaryAction: 'Watch Demonstration',
    icon: 'i',
    status: 'Instruction',
    session: true,
    progress: { current: 8, total: 9 },
    cards: ['Chair against wall', 'Feet flat', 'Arms crossed'],
  },
  {
    id: 'display_chair_live',
    namespace: 'display',
    path: '/display/assessment/chair/live',
    title: '30-Second Chair Stand Test',
    eyebrow: '30-Second Chair Stand Test',
    instruction: 'Stand all the way up, then sit all the way down.',
    description: 'The valid repetition count comes from the existing movement logic.',
    primaryAction: 'Pause',
    secondaryAction: 'Hear Again',
    icon: '!',
    status: 'Timed assessment in progress',
    session: true,
    timed: true,
    active: true,
    progress: { current: 8, total: 9 },
    camera: true,
    cards: ['30-second timer', 'Rep counter', 'Stop Session is always available'],
  },
  {
    id: 'display_chair_result',
    namespace: 'display',
    path: '/display/assessment/chair/result',
    title: 'Chair Stand Test Result',
    eyebrow: 'Assessment result',
    instruction: 'Review the saved repetition count before the full summary.',
    description: 'The result shown here comes from the existing assessment pipeline.',
    primaryAction: 'Continue to Results',
    secondaryAction: 'Hear Again',
    icon: 'OK',
    status: 'Assessment complete',
    session: true,
    progress: { current: 9, total: 9 },
    cards: ['Completed stands', 'Camera quality', 'Next step'],
  },
  {
    id: 'display_session_analyzing',
    namespace: 'display',
    path: '/display/session/analyzing',
    title: 'Reviewing Your Movement',
    eyebrow: 'Analysis',
    instruction: 'Steply is preparing the assessment summary from completed measurements.',
    description: 'The existing scoring pipeline prepares the result and exercise plan.',
    primaryAction: 'View Results',
    secondaryAction: 'End assessment',
    icon: 'i',
    status: 'Preparing results',
    session: true,
    progress: { current: 9, total: 9 },
    cards: ['Movement result', 'Fall-risk summary', 'Exercise plan'],
  },
  {
    id: 'display_results_summary',
    namespace: 'display',
    path: '/display/results/summary',
    title: "Today's Movement Check",
    eyebrow: 'Results',
    instruction: "Review today's support level, assessment results, and next action.",
    description: 'Use the details screen if a clinician or caregiver needs more information.',
    primaryAction: 'View My Exercise Plan',
    secondaryAction: 'View Detailed Results',
    icon: 'OK',
    status: 'Summary ready',
    cards: ['Risk status', 'Functional areas', 'Recommended next step'],
  },
  {
    id: 'display_results_details',
    namespace: 'display',
    path: '/display/results/details',
    title: 'Detailed Results',
    eyebrow: 'Details',
    instruction: 'Review assessment results, movement observations, exercise reasoning, and previous results.',
    description: 'This screen displays calculated values passed in from the existing pipeline.',
    primaryAction: 'View My Exercise Plan',
    secondaryAction: 'Back to Summary',
    icon: 'i',
    status: 'Details ready',
    cards: ['CDC STEADI result', '4-Stage Balance Test', '30-Second Chair Stand Test'],
  },
  {
    id: 'display_exercises_plan',
    namespace: 'display',
    path: '/display/exercises/plan',
    title: "Today's Exercise Plan",
    eyebrow: 'Otago Exercise Programme',
    instruction: "Review today's prescribed exercises.",
    description: 'The plan is selected by the existing Otago Exercise Programme mapping.',
    primaryAction: 'Start Exercise Session',
    secondaryAction: 'Split Into Two Short Sessions',
    icon: 'i',
    status: 'Plan ready',
    cards: ['Exercise amount', 'Support requirement', 'Camera feedback'],
  },
  {
    id: 'display_exercise_preview',
    namespace: 'display',
    path: '/display/exercises/:exerciseId/preview',
    title: 'Exercise preview',
    eyebrow: 'Preview',
    instruction: 'Watch the guidance before starting the exercise.',
    description: 'Keep a stable chair, counter, or wall nearby.',
    primaryAction: 'Start Exercise',
    secondaryAction: 'Return to Exercise Plan',
    icon: 'i',
    status: 'Preview',
    cards: ['Starting position', 'Movement sequence', 'Safety note'],
  },
  {
    id: 'display_exercise_live',
    namespace: 'display',
    path: '/display/exercises/:exerciseId/live',
    title: 'Exercise in progress',
    eyebrow: 'Guided exercise',
    instruction: 'Move slowly and keep support nearby.',
    description: 'Pause or stop if you feel unsafe.',
    primaryAction: 'Pause',
    secondaryAction: 'Hear again',
    icon: '!',
    status: 'Exercise in progress',
    session: true,
    timed: true,
    active: true,
    progress: { current: 1, total: 1 },
    camera: true,
    cards: ['Rest timer', 'Safe pace', 'Stop Session is always available'],
  },
  {
    id: 'display_exercise_complete',
    namespace: 'display',
    path: '/display/exercises/:exerciseId/complete',
    title: 'Exercise Complete',
    eyebrow: 'Post-exercise check',
    instruction: 'Check how you felt before moving on.',
    description: 'Your exercise progress is ready to review.',
    primaryAction: 'Continue',
    secondaryAction: 'Return to Exercise Plan',
    icon: 'OK',
    status: 'Exercise complete',
    cards: ['No discomfort', 'Mild difficulty', 'Safety symptoms'],
  },
  {
    id: 'display_session_complete',
    namespace: 'display',
    path: '/display/session/complete',
    title: "Today's Session Is Complete",
    eyebrow: 'Complete',
    instruction: "Today's session is complete.",
    description: 'Review the summary, share a report, or return home.',
    primaryAction: 'Return Home',
    secondaryAction: "View Today's Results",
    icon: 'OK',
    status: 'Complete',
    cards: ['Assessments completed', 'Exercises completed', 'Next reassessment date'],
  },
  {
    id: 'display_progress',
    namespace: 'display',
    path: '/display/progress',
    title: 'Progress',
    eyebrow: 'Progress',
    instruction: 'Review assessment and exercise changes over time.',
    description: 'Valid assessments appear in trend charts. Excluded measurements stay visible in the history list.',
    primaryAction: 'View Weekly Report',
    secondaryAction: 'Return Home',
    icon: 'i',
    status: 'Progress view',
    cards: ['Chair Stand Progress', 'Balance Progress', 'Weekly Exercise Completion'],
  },
  {
    id: 'display_reports',
    namespace: 'display',
    path: '/display/reports',
    title: 'Weekly Report',
    eyebrow: 'Reports',
    instruction: 'Review a clear weekly summary before sharing or exporting.',
    description: 'Reports use existing assessment results, exercise prescription, adherence, safety events, and care actions.',
    primaryAction: 'Share With Caregiver',
    secondaryAction: 'Return Home',
    icon: 'i',
    status: 'Report view',
    cards: ['Support Level', 'Functional Areas', 'Recommended Next Step'],
  },
  {
    id: 'display_settings',
    namespace: 'display',
    path: '/display/settings',
    title: 'Settings',
    eyebrow: 'Settings',
    instruction: 'Adjust display preferences, connection, reminders, and privacy.',
    description: 'Keep text large, contrast clear, voice guidance comfortable, and sharing permissions explicit.',
    primaryAction: 'Save Settings',
    secondaryAction: 'Return Home',
    icon: 'i',
    status: 'Settings',
    cards: ['Accessibility', 'Camera and Connection', 'Privacy'],
  },
  {
    id: 'display_error_state',
    namespace: 'display',
    path: '/display/error/:state',
    title: 'Session Notice',
    eyebrow: 'Session notice',
    instruction: 'Review the message before continuing.',
    description: 'Steply pauses the flow when setup, connection, safety, or review is needed.',
    primaryAction: 'Continue',
    secondaryAction: 'Return Home',
    icon: '!',
    status: 'Action needed',
    cards: ['Camera access', 'Connection lost', 'Invalid assessment', 'Safety stop'],
  },
];

const cameraRoutes = [
  {
    id: 'camera_connect',
    namespace: 'camera',
    path: '/camera/connect',
    title: 'Connect to Display',
    eyebrow: 'Phone camera',
    instruction: 'Scan the QR code or enter the connection code.',
    description: 'This phone will send camera frames to the Steply display.',
    primaryAction: 'Connect to Display',
    secondaryAction: 'Cancel',
    icon: 'i',
    status: 'Waiting to connect',
  },
  {
    id: 'camera_permission',
    namespace: 'camera',
    path: '/camera/permission',
    title: 'Allow camera access',
    eyebrow: 'Permission',
    instruction: 'Allow camera access so the large display can guide the session.',
    description: 'Steply uses the camera only during the active session.',
    primaryAction: 'Allow camera',
    secondaryAction: 'Not now',
    icon: '!',
    status: 'Camera permission needed',
  },
  {
    id: 'camera_preview',
    namespace: 'camera',
    path: '/camera/preview',
    title: 'Preview camera view',
    eyebrow: 'Preview',
    instruction: 'Point the phone so the person is fully visible.',
    description: 'Keep the phone steady before streaming starts.',
    primaryAction: 'Start streaming',
    secondaryAction: 'Adjust later',
    icon: 'i',
    status: 'Preview ready',
    camera: true,
  },
  {
    id: 'camera_streaming',
    namespace: 'camera',
    path: '/camera/streaming',
    title: 'Camera streaming',
    eyebrow: 'Streaming',
    instruction: 'Keep the phone still and pointed at the person.',
    description: 'The large display will give the movement instructions.',
    primaryAction: 'Stop streaming',
    secondaryAction: 'Switch camera',
    icon: 'OK',
    status: 'Streaming to display',
    camera: true,
  },
  {
    id: 'camera_disconnected',
    namespace: 'camera',
    path: '/camera/disconnected',
    title: 'Phone Connection Lost',
    eyebrow: 'Connection lost',
    instruction: 'The assessment has been paused.',
    description: 'Reconnect the phone before continuing.',
    primaryAction: 'Reconnect',
    secondaryAction: 'End Session',
    icon: '!',
    status: 'Connection lost',
  },
  {
    id: 'camera_stopped',
    namespace: 'camera',
    path: '/camera/stopped',
    title: 'Camera stopped',
    eyebrow: 'Stopped',
    instruction: 'The camera stream has stopped.',
    description: 'Return to the large display to continue or end the session.',
    primaryAction: 'Restart camera',
    secondaryAction: 'Done',
    icon: 'OK',
    status: 'Stopped',
  },
];

export const steplyRoutes = [...displayRoutes, ...cameraRoutes];

function normalizePath(pathname) {
  if (!pathname || pathname === '/') return '/';
  return pathname.endsWith('/') && pathname.length > 1 ? pathname.slice(0, -1) : pathname;
}

function matchPattern(pattern, pathname) {
  const patternParts = normalizePath(pattern).split('/').filter(Boolean);
  const pathParts = normalizePath(pathname).split('/').filter(Boolean);
  if (patternParts.length !== pathParts.length) return null;

  return patternParts.reduce((params, part, index) => {
    if (params === null) return null;
    const value = pathParts[index];
    if (part.startsWith(':')) {
      return { ...params, [part.slice(1)]: decodeURIComponent(value) };
    }
    return part === value ? params : null;
  }, {});
}

export function matchSteplyRoute(pathname) {
  const normalizedPath = normalizePath(pathname);
  for (const route of steplyRoutes) {
    const params = matchPattern(route.path, normalizedPath);
    if (params) return { ...route, params };
  }
  return null;
}

export function isSteplyFoundationPath(pathname) {
  const normalizedPath = normalizePath(pathname);
  return normalizedPath.startsWith('/display') || normalizedPath.startsWith('/camera');
}
