export const PoseLandmarks = {
  Nose: 'nose',
  LeftShoulder: 'left_shoulder',
  RightShoulder: 'right_shoulder',
  LeftElbow: 'left_elbow',
  RightElbow: 'right_elbow',
  LeftWrist: 'left_wrist',
  RightWrist: 'right_wrist',
  LeftHip: 'left_hip',
  RightHip: 'right_hip',
  LeftKnee: 'left_knee',
  RightKnee: 'right_knee',
  LeftAnkle: 'left_ankle',
  RightAnkle: 'right_ankle',
  LeftHeel: 'left_heel',
  RightHeel: 'right_heel',
  LeftFootIndex: 'left_foot_index',
  RightFootIndex: 'right_foot_index',
};

export const MediaPipePoseNames = [
  PoseLandmarks.Nose,
  'left_eye_inner',
  'left_eye',
  'left_eye_outer',
  'right_eye_inner',
  'right_eye',
  'right_eye_outer',
  'left_ear',
  'right_ear',
  'mouth_left',
  'mouth_right',
  PoseLandmarks.LeftShoulder,
  PoseLandmarks.RightShoulder,
  PoseLandmarks.LeftElbow,
  PoseLandmarks.RightElbow,
  PoseLandmarks.LeftWrist,
  PoseLandmarks.RightWrist,
  'left_pinky',
  'right_pinky',
  'left_index',
  'right_index',
  'left_thumb',
  'right_thumb',
  PoseLandmarks.LeftHip,
  PoseLandmarks.RightHip,
  PoseLandmarks.LeftKnee,
  PoseLandmarks.RightKnee,
  PoseLandmarks.LeftAnkle,
  PoseLandmarks.RightAnkle,
  PoseLandmarks.LeftHeel,
  PoseLandmarks.RightHeel,
  PoseLandmarks.LeftFootIndex,
  PoseLandmarks.RightFootIndex,
];

export const RequiredChairStandLandmarks = [
  PoseLandmarks.LeftShoulder,
  PoseLandmarks.RightShoulder,
  PoseLandmarks.LeftHip,
  PoseLandmarks.RightHip,
  PoseLandmarks.LeftKnee,
  PoseLandmarks.RightKnee,
  PoseLandmarks.LeftAnkle,
  PoseLandmarks.RightAnkle,
];

export const PoseConnections = [
  [PoseLandmarks.LeftShoulder, PoseLandmarks.RightShoulder],
  [PoseLandmarks.LeftShoulder, PoseLandmarks.LeftElbow],
  [PoseLandmarks.LeftElbow, PoseLandmarks.LeftWrist],
  [PoseLandmarks.RightShoulder, PoseLandmarks.RightElbow],
  [PoseLandmarks.RightElbow, PoseLandmarks.RightWrist],
  [PoseLandmarks.LeftShoulder, PoseLandmarks.LeftHip],
  [PoseLandmarks.RightShoulder, PoseLandmarks.RightHip],
  [PoseLandmarks.LeftHip, PoseLandmarks.RightHip],
  [PoseLandmarks.LeftHip, PoseLandmarks.LeftKnee],
  [PoseLandmarks.LeftKnee, PoseLandmarks.LeftAnkle],
  [PoseLandmarks.RightHip, PoseLandmarks.RightKnee],
  [PoseLandmarks.RightKnee, PoseLandmarks.RightAnkle],
];
