export const BALANCE_CONFIG_VERSION = 'balance_config.v1';

export const balanceConfig = {
  version: BALANCE_CONFIG_VERSION,
  legacyResultSchemaVersion: 'balance_result.v1',
  targetHoldSeconds: 10,
  dynamicAdjustmentSeconds: 3.5,
  entryConfirmMs: 650,
  exitConfirmMs: 700,
  minStanceConfidence: 0.35,
  footMovementExitThreshold: 0.16,
  footMovementExitConfirmFrames: 3,
  handSupportRatioThreshold: 0.12,
  stageOrder: ['SIDE_BY_SIDE', 'SEMI_TANDEM', 'TANDEM', 'ONE_LEG'],
  camera: {
    minFootLandmarkConfidence: 0.55,
    minFootPlaneObservableScore: 0.55,
    minFootVectorVerticalComponent: 0.18,
    maxFootOcclusionCenterDistanceFootLengths: 0.42,
    ambiguousUserMessage: 'Turn slightly so the camera can see both feet.',
    feetVisibleUserMessage: 'Keep both heels and toes visible.',
    positionGuideUserMessage: 'Move your feet to match the guide.',
  },
  position: {
    confirmationDwellMs: 650,
    minimumTargetScore: 0.72,
    minimumScoreMargin: 0.14,
    minimumFootConfidence: 0.55,
    sideBySide: {
      lateralMinFootLengths: 1.15,
      lateralMaxFootLengths: 2.8,
      anteriorPosteriorMaxFootLengths: 0.42,
      parallelMin: 0.55,
    },
    semiTandem: {
      lateralMinFootLengths: 0.45,
      lateralMaxFootLengths: 1.45,
      anteriorPosteriorMinFootLengths: 0.45,
      anteriorPosteriorMaxFootLengths: 1.35,
      heelToeGapMinFootLengths: 0.35,
      heelToeGapMaxFootLengths: 1.35,
      parallelMin: 0.45,
    },
    tandem: {
      lateralMaxFootLengths: 0.55,
      anteriorPosteriorMinFootLengths: 0.82,
      anteriorPosteriorMaxFootLengths: 1.75,
      heelToeGapMaxFootLengths: 0.58,
      parallelMin: 0.45,
    },
    oneLeg: {
      liftedFootMinHeightFootLengths: 0.62,
      supportFootMaxMovementFootLengths: 0.35,
      pelvisInFrameMargin: 0.04,
    },
  },
  hold: {
    targetHoldMs: 10_000,
    footMoveDistanceFootLengths: 0.55,
    footMoveDwellMs: 450,
    positionLostDwellMs: 550,
    liftedFootTouchDownDwellMs: 350,
    jitterIgnoreDistanceFootLengths: 0.18,
    cameraMotionFootShiftFootLengths: 0.75,
  },
  support: {
    enabledWithoutRoi: false,
    wristConfidenceMin: 0.55,
    roiDwellMs: 450,
  },
};
