import { stage2Operational } from './stage2Analysis.config.js';

export const CHAIR_STAND_CONFIG_VERSION = 'chair_stand_config.v2';

export const chairStandConfig = {
  version: CHAIR_STAND_CONFIG_VERSION,
  durationSeconds: stage2Operational.chairStand.durationMs / 1000,
  legacyResultSchemaVersion: 'chair_stand_result.v1',
  partialRepetitionRuleStatus: 'APPLIED',
  stateMachine: {
    angleMovingAverageFrames: stage2Operational.signal.angleMovingAverageFrames,
    angularVelocityMovingAverageFrames: stage2Operational.signal.angularVelocityMovingAverageFrames,
    sitProgressMax: stage2Operational.chairStand.sitHipHeightFraction,
    sitEnterProgressMax: stage2Operational.chairStand.sitHipHeightFraction,
    sitExitProgressMin: stage2Operational.chairStand.sitHipHeightFraction,
    standProgressMin: stage2Operational.chairStand.standHipHeightFraction,
    standExitProgressMax: stage2Operational.chairStand.standHipHeightFraction,
    minimumRisingVelocityPerSecond: stage2Operational.chairStand.minimumTransitionVelocityPerSecond,
    minimumDescendingVelocityPerSecond: stage2Operational.chairStand.minimumTransitionVelocityPerSecond,
    minimumSitDwellMs: stage2Operational.chairStand.minimumStateDwellMs,
    minimumStandDwellMs: stage2Operational.chairStand.minimumStateDwellMs,
    minimumTransitionDwellMs: stage2Operational.chairStand.minimumStateDwellMs,
    minimumLandmarkConfidence: stage2Operational.chairStand.minimumLandmarkConfidence,
    sittingKneeAngleMaxDegrees: stage2Operational.chairStand.sitKneeEnterDegrees,
    sittingKneeExitDegrees: stage2Operational.chairStand.sitKneeExitDegrees,
    sittingHipAngleMaxDegrees: stage2Operational.chairStand.sittingHipAngleMaxDegrees,
    standingKneeAngleMinDegrees: stage2Operational.chairStand.standKneeEnterDegrees,
    standingKneeExitDegrees: stage2Operational.chairStand.standKneeExitDegrees,
    standingHipAngleMinDegrees: stage2Operational.chairStand.standHipEnterDegrees,
    partialRepetitionCreditProgressMin: stage2Operational.chairStand.halfRiseFraction,
    partialRepetitionRequiresRisingState: true,
    asymmetryRatio: stage2Operational.chairStand.asymmetryRatio,
  },
  armUse: {
    foldedConfirmDwellMs: stage2Operational.chairStand.foldedConfirmDwellMs,
    suspectedDwellMs: stage2Operational.chairStand.armUseDwellMs,
    confirmedDwellMs: stage2Operational.chairStand.armUseDwellMs,
    foldedDistanceMultiplier: stage2Operational.chairStand.armFoldDistanceMultiplier,
    maximumRestartCount: stage2Operational.chairStand.maximumRestartCount,
    minArmLandmarkConfidence: stage2Operational.chairStand.minimumArmLandmarkConfidence,
    minConfirmedArmConfidence: stage2Operational.chairStand.minimumConfirmedArmConfidence,
    chestHorizontalMarginShoulderWidths: stage2Operational.chairStand.chestHorizontalMarginShoulderWidths,
    chestVerticalMarginTorsoLengths: stage2Operational.chairStand.chestVerticalMarginTorsoLengths,
    thighRegionMarginTorsoLengths: stage2Operational.chairStand.thighRegionMarginTorsoLengths,
  },
  geometry: {
    minimumVisibility: stage2Operational.chairStand.geometryMinimumVisibility,
    armMinimumVisibility: stage2Operational.chairStand.armGeometryMinimumVisibility,
    fallbackShoulderWidthMeters: stage2Operational.chairStand.fallbackShoulderWidthMeters,
    fallbackTorsoLengthMeters: stage2Operational.chairStand.fallbackTorsoLengthMeters,
  },
};
