export const CHAIR_STAND_CONFIG_VERSION = 'chair_stand_config.v1';

export const chairStandConfig = {
  version: CHAIR_STAND_CONFIG_VERSION,
  durationSeconds: 30,
  legacyResultSchemaVersion: 'chair_stand_result.v1',
  partialRepetitionRuleStatus: 'NOT_IMPLEMENTED',
  stateMachine: {
    sitProgressMax: 0.22,
    sitEnterProgressMax: 0.28,
    sitExitProgressMin: 0.3,
    standProgressMin: 0.82,
    standExitProgressMax: 0.72,
    minimumRisingVelocityPerSecond: 0.18,
    minimumDescendingVelocityPerSecond: -0.18,
    minimumSitDwellMs: 220,
    minimumStandDwellMs: 260,
    minimumTransitionDwellMs: 120,
    repRefractoryMs: 650,
    lowConfidencePauseThreshold: 0.45,
    minimumLandmarkConfidence: 0.5,
    footStabilityMaxDisplacementFootLengths: 0.42,
    sittingKneeAngleMaxDegrees: 128,
    sittingHipAngleMaxDegrees: 135,
    standingKneeAngleMinDegrees: 148,
    standingHipAngleMinDegrees: 145,
    partialRepetitionCreditProgressMin: 0.5,
    partialRepetitionRequiresRisingState: true,
  },
  armUse: {
    foldedConfirmDwellMs: 350,
    suspectedDwellMs: 300,
    confirmedDwellMs: 450,
    minArmLandmarkConfidence: 0.35,
    minConfirmedArmConfidence: 0.55,
    chestHorizontalMarginShoulderWidths: 0.55,
    chestVerticalMarginTorsoLengths: 0.2,
    thighRegionMarginTorsoLengths: 0.18,
  },
};
