import { stage2Operational } from './stage2Analysis.config.js';

export const QUALITY_CONFIG_VERSION = 'quality_config.v2';

export const qualityConfig = {
  version: QUALITY_CONFIG_VERSION,
  trackingQualityAllow: stage2Operational.quality.trackingQualityAllow,
  trackingQualityMinResult: stage2Operational.quality.trackingQualityMinimumResult,
  minVisibility: stage2Operational.quality.minimumVisibility,
  minBodyHeight: stage2Operational.quality.minimumBodyHeight,
  maxBodyHeight: stage2Operational.quality.maximumBodyHeight,
  maxCenterJumpRatio: stage2Operational.quality.maximumCenterJumpRatio,
  maxSizeChangeRatio: stage2Operational.quality.maximumSizeChangeRatio,
  sessionMinAcceptedFrames: stage2Operational.quality.sessionMinimumAcceptedFrames,
  sessionLowQualityRatioLimit: stage2Operational.quality.legacySessionLowQualityRatioLimit,
  shortLossHoldMs: 0,
  pauseAfterLossMs: stage2Operational.quality.violationPersistenceMs,
  invalidAfterLossMs: Number.POSITIVE_INFINITY,
  resumeStableMs: stage2Operational.quality.resumeStableMs,
  maxAccumulatedPauseRatio: stage2Operational.quality.invalidViolationRatioExclusive,
  minOverallConfidence: stage2Operational.quality.minimumOverallConfidence,
  minLowerBodyConfidence: stage2Operational.quality.minimumLowerBodyConfidence,
  minFeetConfidence: stage2Operational.quality.minimumFeetConfidence,
  minBodyInFrameScore: stage2Operational.quality.minimumBodyInFrameScore,
  minCameraOrientationScore: stage2Operational.quality.minimumCameraOrientationScore,
  minLightingScore: stage2Operational.quality.minimumLightingScore,
  lowLightBrightness: stage2Operational.quality.brightnessMinNormalized,
  highLightBrightness: stage2Operational.quality.brightnessMaxNormalized,
  coreLandmarkStart: stage2Operational.quality.coreLandmarkStart,
  coreLandmarkEnd: stage2Operational.quality.coreLandmarkEnd,
  frameMargin: stage2Operational.quality.frameMargin,
  frontalShoulderWidthRatio: stage2Operational.quality.frontalShoulderWidthRatio,
  footPlacementObservableMinScore: stage2Operational.quality.minimumFootPlacementObservableScore,
  footFrameMargin: stage2Operational.quality.footFrameMargin,
  footFrameMinimumVisibility: stage2Operational.quality.footFrameMinimumVisibility,
  chairPreferredCameraScore: stage2Operational.quality.chairPreferredCameraScore,
  chairRejectedCameraScore: stage2Operational.quality.chairRejectedCameraScore,
};
