import {
  Accessibility,
  Activity,
  Armchair,
  ArrowLeft,
  ArrowRight,
  Award,
  Bell,
  BookOpen,
  CalendarCheck2,
  CalendarDays,
  CalendarPlus,
  Camera,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Crosshair,
  Download,
  Dumbbell,
  Eye,
  FileText,
  Flag,
  Flame,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Lightbulb,
  Link,
  ListChecks,
  MoveHorizontal,
  Pause,
  PersonStanding,
  Play,
  Repeat2,
  Scale,
  ScanLine,
  ScanQrCode,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Star,
  Sun,
  Target,
  Timer,
  TrendingUp,
  Type,
  UserRound,
  UserRoundCheck,
  Users,
  X,
  Zap,
} from 'lucide-react';

const ICONS = {
  accessibility: Accessibility,
  activity: Activity,
  armchair: Armchair,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  award: Award,
  bell: Bell,
  bookOpen: BookOpen,
  calendarCheck: CalendarCheck2,
  calendarDays: CalendarDays,
  calendarPlus: CalendarPlus,
  camera: Camera,
  chart: ChartNoAxesColumnIncreasing,
  chartTrend: ChartNoAxesCombined,
  check: Check,
  chevronDown: ChevronDown,
  circleCheck: CircleCheck,
  help: CircleHelp,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  crosshair: Crosshair,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  fileText: FileText,
  flag: Flag,
  flame: Flame,
  heart: Heart,
  heartPulse: HeartPulse,
  home: Home,
  laptop: Laptop,
  lightbulb: Lightbulb,
  link: Link,
  listChecks: ListChecks,
  moveHorizontal: MoveHorizontal,
  pause: Pause,
  personStanding: PersonStanding,
  play: Play,
  repeat: Repeat2,
  scale: Scale,
  scan: ScanLine,
  scanQr: ScanQrCode,
  settings: Settings,
  share: Share2,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  smartphone: Smartphone,
  star: Star,
  sun: Sun,
  target: Target,
  timer: Timer,
  trendingUp: TrendingUp,
  type: Type,
  user: UserRound,
  userCheck: UserRoundCheck,
  users: Users,
  close: X,
  zap: Zap,
};

export function SteplyIcon({ name, size = 20, strokeWidth = 1.8, className = '' }) {
  const IconComponent = ICONS[name];
  if (!IconComponent) return null;

  return (
    <IconComponent
      className={`ref-icon${className ? ` ${className}` : ''}`}
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      focusable="false"
    />
  );
}
